spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/contributorDB?useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: root
    sql-script-encoding: UTF-8
    tomcat:
      connection-properties: useUnicode=true;characterEncoding=utf-8;
    platform: org.hibernate.dialect.MySQL5InnoDBDialect
  jpa:
    hibernate.ddl-auto: update
    generate-ddl: true
    show-sql: true
  thymeleaf:
    cache: false
server:
  port: 8080

