spring:
  web:
    locale: US
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/contributordb?useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: root
    sql-script-encoding: UTF-8
    tomcat:
      connection-properties: useUnicode=true;characterEncoding=utf-8;
    platform: org.hibernate.dialect.MySQL5InnoDBDialect
  jpa:
    hibernate.ddl-auto: update
    generate-ddl: true
    show-sql: true
  thymeleaf:
    cache: false
  profiles:
    active:
  mail:
    host: smtp.gmail.com
    port: 587
    username: test.za.javu.smtp@gmail.com
    password: testjava123
    protocol: smtp
    properties:
      mail:
        smtp:
          auth: true
          connectiontimeout: 5000
          timeout: 3000
          writetimeout: 5000
          starttls:
            enable: true
    test-connection: false


